### ISSUE TITLE
Search parameters for Ingredient (reference strength substance)

### ISSUE THREAD

**Issue by a-gkogkidis** [hl7-eu/unicom-ig#100]
So, I know Rutt will kill me for delaying this, but is it possible to search ingredient for 
referenceStrength > Substance > Code?
Like in the image bellow
![image](https://user-images.githubusercontent.com/116799621/215036322-4bb4c5d5-4eca-40f5-959a-11db53bc3fd5.png)

**Comment by rlindstrm** [comment]
Can I assign it to two people at the same time?

@costateixeira makes the search parameter work and adds it to the IG and DW server.
@rlindstrm kills Argiris for delaying with issues.

**Comment by rlindstrm** [comment]
José says reindexing does not work in R4B HAPI, so we can add search parameters only after switching to R5.

**Comment by joofio** [comment]
the SearchParameter should be something like this:
```
{
  "resourceType" : "SearchParameter",
  "id":207,
  "status" : "active",
  "code" : "reference-strength-substance",
  "base" : ["Ingredient"],
  "type" : "token",
  "expression" : "Ingredient.substance.strength.referenceStrength.substance.concept",
  "processingMode" : "normal"
}
```

Uploading this to HAPI FHIR, automatically creates the search parameter.

Please test and if ok, we add it to the IG.

**Comment by costateixeira** [comment]
http://185.11.167.107:8085/fhir/SearchParameter/sp-refstrength-substance

and it works:
http://185.11.167.107:8085/fhir/Ingredient?ref-strength-substance=100000085259

**Comment by joofio** [comment]
adding it to the IG

**Comment by a-gkogkidis** [comment]
Tested also in Java. Seems to be working.
