### ISSUE TITLE
Merging and moving to R5 (sequence of actions)

### ISSUE THREAD

**Issue by rlindstrm** [hl7-eu/unicom-ig#101]
Let's go through this in the meeting to make sure we're not forgetting something:

**template-work** branch to be merged to **master**
**master** to be merged to **mpd-r4b** (will be conserved, needs a special introduction/disclaimer and maybe link from master IG)
**master** to be merged/converted to **mpd-r5** or similar, which will be the new branch for continuous work.
**mpd-r5** back to **master** when we see it works well in R5.

Decide which branches we could get rid of.

**Comment by joofio** [comment]
1.  **template-work** branch to be merged to master
2. validate if master needs to be merged into mpd-r4b (will be conserved, needs a special introduction/disclaimer and maybe link from master IG) or just template-work branch into mpd-r4b

3. merge master into mpd-r5 to validate which will be the new branch for continuous work.
4. after validation (and possible corrections) merge mpd-r5 back to master when we see it works well in R5.

**Comment by rlindstrm** [comment]
MPD-R4B done and validated (I will do the disclaimers and stuff)
MPD-R5 done and validated. Shows 0 errors in web build qa, so I guess we're ready to merge mpd-r5 back to master. 
(So, back to you, @joofio )

**Comment by joofio** [comment]
build in master from r5 ok:
https://build.fhir.org/ig/hl7-eu/unicom-ig/qa.html
Seems good to close the issue
