### ISSUE TITLE
sql database structure

### ISSUE THREAD

**Issue by rlindstrm** [hl7-eu/unicom-ig#106]
I learned that there are some nice people who would be interested in SQL database schema for our data. Possibly, also mapping to our PPL logical model or FHIR definitional resources, so that it would be easy for them to take our FHIR data and play with it in their SQL database.
Can we reuse d6.1 work and provide that guidance in our IG? Let's discuss.

**Comment by G-DPP** [comment]
The d6.1 is not based on the fhir resources but on the idmp database implementation of the ema. It depends on what kind of data they want to get. If what they want is fhir resources then we could remove h2 as the database and add postgres so they can transfer the data.

**Comment by rlindstrm** [comment]
out of scope right now
