### ISSUE TITLE
Problem searching MedicinalProductDefinition by country in JPA R5

### ISSUE THREAD

**Issue by a-gkogkidis** [hl7-eu/unicom-ig#108]
So, in theory the request in MedicinalProductDefinition by name-language = 100000072172 should retrieve all the Estonian products.. But I get zero

https://jpa.unicom.datawizard.it/fhir/MedicinalProductDefinition?name-language=100000072172

Any ideas? is it HAPI issue? or 5.0.0-ballot

**Comment by rlindstrm** [comment]
I don't see an apparent problem, so @joofio or @costateixeira - maybe you can take a look.

Search parameter is correct and exists in R5 Ballot: http://hl7.org/fhir/2022Sep/medicinalproductdefinition.html#search
Language code is correct.
Matching products exist ([EE Lantus](https://jpa.unicom.datawizard.it/fhir/MedicinalProductDefinition/LantusSolostar-EE-MPD)).

**Comment by costateixeira** [comment]
don't know which of us fixed it, but seems to be working

I added 2 extra parameters, then deleted a few (or all, don't remember).
Maybe DW reindexed everything. Seems to be working
https://jpa.unicom.datawizard.it/fhir/MedicinalProductDefinition?name-language=100000072172

**Comment by a-gkogkidis** [comment]
Indeed seems to be ok.
