### ISSUE TITLE
Data structure in Ingredient resource

### ISSUE THREAD

**Issue by a-gkogkidis** [hl7-eu/unicom-ig#109]
Is the Ingredient resource for reference supposed to always be the same?

https://jpa.unicom.datawizard.it/fhir/Ingredient/CopaliaHCT-ingredient1-EE-I

the above has this JSON 

"for": [ {
        "reference": "MedicinalProductDefinition/CopaliaHCT-EE-MPD"
      }, {
        "reference": "AdministrableProductDefinition/CopaliaHCT-EE-APD"
      }, {
        "reference": "ManufacturedItemDefinition/CopaliaHCT-EE-MID"
      } ],
      
While all the other products have this:

"for": [ {
        "reference": "MedicinalProductDefinition/Agen-5mg-Tablet-EE-MPD"
      }, {
        "reference": "ManufacturedItemDefinition/Agen-5mg-Tablet-EE-MID"
      }, {
        "reference": "AdministrableProductDefinition/Agen-5mg-Tablet-EE-APD"
      } ],

Medicinal then Manufactured then Administrable. Is it a "typo" or there will be cases like this? I am asking to check if substitution should have a validity while it's trying to parse this section of the Ingredient.

**Comment by rlindstrm** [comment]
I believe you cannot assume that the order of the references in Ingredient.for is always the same. There is no such restriction in the specification, and not all references might not even be present (I don't have any such examples right now, but theoretically it may happen).

**Comment by a-gkogkidis** [comment]
Ok, that works for me. It's a small extra loop, but I suppose when someone wants to do performance improvements can figure this out.
