### ISSUE TITLE
Starting jpa server, search parameters don't work

### ISSUE THREAD

**Issue by rlindstrm** [hl7-eu/unicom-ig#114]
Summary of a problem from today's meeting.
When DW server is restarted, search parameters seem to take a very long (several days) before they start functioning. Not sure what triggers them in the end that they eventually start working, but it takes longer than any reindexing process on the background could do.
Posting a search parameter after restart might accelerate things, but is not an actual fix to the real problem.

Simone will ask around in Zulip chat.

**Comment by simodiaco** [comment]
Unfortunately, I have not yet received any reply on Zulip. 
The only search parameter that does not work at the moment is the **name-language**, so I suggest (only temporarily) filtering the MedicinalProductDefinition via the '_content' parameter

Example: https://jpa.unicom.datawizard.it/fhir/MedicinalProductDefinition?_content=greek

We are continuing to work out what the problem should be.

**Comment by joofio** [comment]
So, i think i got it: there is something wrong with the search parameter.

I have created a new one (equal to what should be the original) and tested and worked ok.

code:

```
{
  "resourceType": "SearchParameter",
  "id": "name-language-correct",
  "url": "http://unicom-project.eu/fhir/SearchParameter/name-language-correct",
  "status": "active",
  "name": "name-language-correct",
  "description": "Possiblity to search ingredient for substance.strength.referenceStrength.substance.concept",
  "code": "name-language-correct",
  "base": [
    "MedicinalProductDefinition"
  ],
  "type": "token",
  "expression": "MedicinalProductDefinition.name.usage.language",
  "processingMode": "normal"
}
```

and then search:

```
<BASE_URL>/MedicinalProductDefinition?name-language-correct=https%3A%2F%2Fspor.ema.europa.eu%2Fv1%2Flists%2F100000072057%7C100000072181
```


Tests:

```
http://fhir.hl7.pt:8080/fhir/MedicinalProductDefinition?name-language-correct=https%3A%2F%2Fspor.ema.europa.eu%2Fv1%2Flists%2F100000072057%7C100000072181
```
The above one works

```
http://fhir.hl7.pt:8080/fhir/MedicinalProductDefinition?name-language=https%3A%2F%2Fspor.ema.europa.eu%2Fv1%2Flists%2F100000072057%7C100000072181
```

The above one doesnt.

Please check in your server to make sure (I did not want to pollute it with tests) and report back pls.

@costateixeira if this is confirmed, something to talk with Jens?

**Comment by costateixeira** [comment]
what is the difference to the original name-language parameter?

**Comment by joofio** [comment]
none, at least **in theory**

**Comment by G-DPP** [comment]
We added the **name-language-correct** parameter to the server and it seems to be working
`https://jpa.unicom.datawizard.it/fhir/MedicinalProductDefinition?name-language-correct=100000072181`

We also tried to do the $reindex and the $mark-all-resources-for-reindexing but the name-language still doesn't seem to work.

In addition, we noticed some strange messages on the logs

```hapiR5  | 2023-03-07 09:36:51.050 [hapi-fhir-jpa-scheduler-local-2] WARN  c.u.f.j.t.TermDeferredStorageSvcImpl [TermDeferredStorageSvcImpl.java:193] Unable to save deferred TermConcept 100000072215 because Code System Language_EMA_CS version PID 139 is no longer valid. Code system may have since been replaced.
hapiR5  | 2023-03-07 09:36:51.050 [hapi-fhir-jpa-scheduler-local-2] WARN  c.u.f.j.t.TermDeferredStorageSvcImpl [TermDeferredStorageSvcImpl.java:193] Unable to save deferred TermConcept 100000072164 because Code System Language_EMA_CS version PID 139 is no longer valid. Code system may have since been replaced.
hapiR5  | 2023-03-07 09:36:51.051 [hapi-fhir-jpa-scheduler-local-2] WARN  c.u.f.j.t.TermDeferredStorageSvcImpl [TermDeferredStorageSvcImpl.java:193] Unable to save deferred TermConcept 100000072300 because Code System Language_EMA_CS version PID 139 is no longer valid. Code system may have since been replaced.
hapiR5  | 2023-03-07 09:36:51.051 [hapi-fhir-jpa-scheduler-local-2] WARN  c.u.f.j.t.TermDeferredStorageSvcImpl [TermDeferredStorageSvcImpl.java:193] Unable to save deferred TermConcept 100000072189 because Code System Language_EMA_CS version PID 139 is no longer valid. Code system may have since been replaced.
hapiR5  | 2023-03-07 09:36:51.051 [hapi-fhir-jpa-scheduler-local-2] WARN  c.u.f.j.t.TermDeferredStorageSvcImpl [TermDeferredStorageSvcImpl.java:193] Unable to save deferred TermConcept 100000072158 because Code System Language_EMA_CS version PID 139 is no longer valid. Code system may have since been replaced.
hapiR5  | 2023-03-07 09:36:51.051 [hapi-fhir-jpa-scheduler-local-2] WARN  c.u.f.j.t.TermDeferredStorageSvcImpl [TermDeferredStorageSvcImpl.java:193] Unable to save deferred TermConcept 100000072232 because Code System Language_EMA_CS version PID 139 is no longer valid. Code system may have since been replaced.
hapiR5  | 2023-03-07 09:36:51.051 [hapi-fhir-jpa-scheduler-local-2] WARN  c.u.f.j.t.TermDeferredStorageSvcImpl [TermDeferredStorageSvcImpl.java:193] Unable to save deferred TermConcept 100000072193 because Code System Language_EMA_CS version PID 139 is no longer valid. Code system may have since been replaced.
hapiR5  | 2023-03-07 09:36:51.051 [hapi-fhir-jpa-scheduler-local-2] WARN  c.u.f.j.t.TermDeferredStorageSvcImpl [TermDeferredStorageSvcImpl.java:193] Unable to save deferred TermConcept 100000072187 because Code System Language_EMA_CS version PID 139 is no longer valid. Code system may have since been replaced.
hapiR5  | 2023-03-07 09:36:51.051 [hapi-fhir-jpa-scheduler-local-2] WARN  c.u.f.j.t.TermDeferredStorageSvcImpl [TermDeferredStorageSvcImpl.java:193] Unable to save deferred TermConcept 100000072125 because Code System Language_EMA_CS version PID 139 is no longer valid. Code system may have since been replaced.
hapiR5  | 2023-03-07 09:36:51.051 [hapi-fhir-jpa-scheduler-local-2] WARN  c.u.f.j.t.TermDeferredStorageSvcImpl [TermDeferredStorageSvcImpl.java:193] Unable to save deferred TermConcept 100000072156 because Code System Language_EMA_CS version PID 139 is no longer valid. Code system may have since been replaced.
hapiR5  | 2023-03-07 09:36:51.051 [hapi-fhir-jpa-scheduler-local-2] WARN  c.u.f.j.t.TermDeferredStorageSvcImpl [TermDeferredStorageSvcImpl.java:193] Unable to save deferred TermConcept 100000072208 because Code System Language_EMA_CS version PID 139 is no longer valid. Code system may have since been replaced.
```
I don't quite understand what these logs refer to and this message also appears for the other code-systems so I don't think it can be related to this issue but I share them anyway

**Comment by joofio** [comment]
the $reindex should not help on that searchParameter. I have asked on zulip but I suspect is an error on that specific searchParameter

**Comment by simodiaco** [comment]
I think the search parameter at this point should be for country.

We had chosen to use name-language because it was a default search parameter, but since that parameter does not work and we have to create a custom search parameter I suggest creating and using a search parameter for the MedicationProductDefinition by country.

For the pilot it is indifferent to use "name-language" rather than "country" since we have different countries and languages, but in the future it will be necessary to use the country parameter because filtering by languages might return wrong medicines.

I had made a test and invite you to test it too. Here is an example:
https://jpa.unicom.datawizard.it/fhir/MedicinalProductDefinition?country=100000000406

**Comment by joofio** [comment]
Seems ok!!!
Can you add it to the repo for future reference?

I will add the new name-language also so we dont miss anything
--

*João Almeida*
MPharm, Msc, PhD Student
LinkedIn <https://www.linkedin.com/in/joaofilipealmeida/> | ORCID
<https://orcid.org/0000-0003-0882-6547> | Website <http://joaofcalmeida.pt>
| gitHub <https://github.com/joofio> |
e-Mais <http://e-mais.pt>| HL7 Portugal <http://hl7.pt> | ***@***.***
<http://cintesis.med.up.pt/> | IHE Pharmacy <http://ihe.net>


Simone Diaco ***@***.***> escreveu no dia quarta, 8/03/2023
à(s) 09:05:

**Comment by simodiaco** [comment]
I created a pull request because I do not have permissions to modify the repository. 
Maybe if it is possible to give permissions both Giuseppe and I  it would be better for the future.

**Comment by rlindstrm** [comment]
I gave you both permissions. Did not realise you didn't have them already. :)
[Joao's thread in Zulip.](https://chat.fhir.org/#narrow/stream/179167-hapi/topic/MedicinalProductDefinition.20search.20parameter.20not.20working.3F)
[José's thread in Zulip.](https://chat.fhir.org/#narrow/stream/179167-hapi/topic/custom.20search.20parameters.20not.20working.20properly)
