### ISSUE TITLE
create profiles from model

### ISSUE THREAD

**Issue by costateixeira** [hl7-eu/unicom-ig#12]

**Comment by rlindstrm** [comment]
Profiling info: https://docs.google.com/spreadsheets/d/1YvNF4s0BoMrZg9qsH-PdCRdDVGHXMpqmRcWl5hFj3os/edit?usp=sharing

**Comment by rlindstrm** [comment]
Done https://build.fhir.org/ig/hl7-eu/unicom-ig/branches/mpd-r4b/artifacts.html
