### ISSUE TITLE
Product viewer: make validation for Bundle instead of only MedicinalProductDefinition

### ISSUE THREAD

**Issue by rlindstrm** [hl7-eu/unicom-ig#120]
Datawizard's product viewer's Validation button only validates MedicinalProductDefinition, not the whole product (which would be a Bundle in FHIR terms).

**Comment by costateixeira** [comment]
The problem is that apparently we don't have a Bundle on the server. We can't validate a searchset bundle

**Comment by rlindstrm** [comment]
For some products, bundles already are in the IG. Possibly you want some other type of bundle, because the validation still only works for MedicinalProductDefinition resource.

We are not going to have thousands of products in the IG. I don't know what needs to be changed in scripts to bundle up products in the importing process.

**Comment by joofio** [comment]
can we validate a document or collection?

**Comment by rlindstrm** [comment]
Done for UNICOM Toolbox
