### ISSUE TITLE
Name.usage.language binding change

### ISSUE THREAD

**Issue by rlindstrm** [hl7-eu/unicom-ig#122]
According to EMA IG, language is coded with EMA SPOR codes for languages (numeric codes).
FHIR 5.0.0 version has required binding to AllLanguages, which is based on BCP-47.
1) Change the required bindings to remove errors.
2) Add description of this problem to Known Issues.

**Comment by joofio** [comment]
missing where? Can you provide an example? I have been changing the language formats to correct errors. This is in fact an issue to be addressed.
