### ISSUE TITLE
A lot of new errors in MPD-R5 branch

### ISSUE THREAD

**Issue by rlindstrm** [hl7-eu/unicom-ig#123]
1) Unable to find a match for profile...
2) The Extension 'http://hl7.org/fhir/tools/StructureDefinition/binding-definition' definition allows for the types [markdown] but found type string

I don't know what to do with them. They appeared after version change.

**Comment by rlindstrm** [comment]
@joofio made 90% of the errors go away, but I still see a lot of the following:
The Extension 'http://hl7.org/fhir/tools/StructureDefinition/binding-definition' definition allows for the types [markdown] but found type string

Also warnings about bundle entries not matching fullurls.

**Comment by joofio** [comment]
The errors are going to be corrected soon. It is not due to the content:
check: https://chat.fhir.org/#narrow/stream/179252-IG-creation/topic/binding-definition.20error

**Comment by joofio** [comment]
http://build.fhir.org/ig/hl7-eu/unicom-ig/branches/mpd-r5/qa.html
Done for now
