### ISSUE TITLE
Do we enrich medication or the clinical document?

### ISSUE THREAD

**Issue by costateixeira** [hl7-eu/unicom-ig#14]
To discuss what is better / aligned with existing implementations:
If we need to add SPOR attributes to a medication for it to be cross-border compatible, where does it go? Do we extend the document (prescription, etc), or the medication part inside the document?

**Comment by costateixeira** [comment]
http://build.fhir.org/ig/hl7-eu/unicom-ig/branches/r4-clinical/alternatives.html

**Comment by rlindstrm** [comment]
This will be part of a new issue.
