### ISSUE TITLE
PackagedProductDefinition.description - cardinality and language

### ISSUE THREAD

**Issue by rlindstrm** [hl7-eu/unicom-ig#15]
Current specification allows only one description without specifying the language. For multilingual countries this might be a problem, as the standard translations might not be clear/fair enough. 

![image](https://user-images.githubusercontent.com/112903984/194927331-debc5e46-d89c-4075-ac48-91ff03e6f35e.png)

EMA implementation uses extension to indicate the language. 
```
				<description value="Üks vaginaalpehmekapsel on blistris, mis koosneb läbipaistvast kolmekordsest PVC/PVdC/PVC laminaatkilest ja on suletud alumiiniumfooliumist kattega. Blister ja polüpropüleenist aplikaator on pakendatud kartongkarpi. ">
					<extension url="https://ema.europa.eu/fhir/extension/language">
						<valueCoding>
							<system value="https://spor.ema.europa.eu/v1/lists/100000072057"/>
							<code value="100000072172"/>
							<display value="Estonian"/>
						</valueCoding>
					</extension>
				</description>
```

In MedicinalProductDefinition.name, FHIR spec presents a different approach with country and name clearly indicated.
![image](https://user-images.githubusercontent.com/112903984/194928272-7fce267f-2bed-453d-b6df-ad07d40a077c.png)

Should be discussed whether the current solution satisfies users or if a more consistent approach should be considered.

**Comment by gcangioli** [comment]
Any resource may define the language in the metadata.
Any human readable element may use the translation extension to convey additional translations see https://build.fhir.org/languages.html#ext 

Is this not enough ?

**Comment by rlindstrm** [comment]
I don't know. Noticed by EE and SE, and we don't really need it anyway, because we only have one official language.
We just noticed that the product name has a special language attribute while package description does not, so EMA has created their own extension for it. 

I guess for multilingual countries it might be a bit of a political issue to choose which one of your languages is the 'real' one and which are given as translations. But you're right, technically it's not much of a problem. 

My next question is, is the EMA implementation (see xml example above) good? Using a self-defined extension to indicate the language of a text block? ([EMA IG](https://www.ema.europa.eu/en/documents/regulatory-procedural-guideline/product-management-services-pms-implementation-international-organization-standardization-iso_en-0.pdf), ch 4.2.1)

**Comment by gcangioli** [comment]
> My next question is, is the EMA implementation (see xml example above) good? Using a self-defined extension to indicate the language of a text block? ([EMA IG](https://www.ema.europa.eu/en/documents/regulatory-procedural-guideline/product-management-services-pms-implementation-international-organization-standardization-iso_en-0.pdf), ch 4.2.1)

I don't know .. we should ask them...I suppose there is a reason if they did it

the only thing I can see is that translation uses a code for the language, may they need to have a CodeableConcept.. but I'm guessing...

**Comment by costateixeira** [comment]
https://jira.hl7.org/browse/FHIR-39128
