### ISSUE TITLE
PackagedProductDefinition: rename containedItemQuantity

### ISSUE THREAD

**Issue by rlindstrm** [hl7-eu/unicom-ig#16]
PackagedProductDefinition contains containedItemQuantity and package.containedItem.amount:

![image](https://user-images.githubusercontent.com/112903984/194929284-ffb834ea-d73c-44fe-bb5a-b55be7dbbfed.png)
[..................................]
![image](https://user-images.githubusercontent.com/112903984/194929397-333315ef-1034-4caa-ad5e-4396c402d17c.png)

It has been indicated that very similar names for these attributes cause confusion. 
We suggest renaming containedItemQuantity into packSize or totalAmount to be absolutely clear what it is used for.

**Comment by gcangioli** [comment]
has been this item added as jira comment already ?

**Comment by rlindstrm** [comment]
Not by me. I am not advanced enough for that, I just filed everything here.

**Comment by rastegwee** [comment]
Not seeing a JIRA issue to vote on.

**Comment by gcangioli** [comment]
https://jira.hl7.org/browse/FHIR-39128

**Comment by rastegwee** [comment]
Thanks! It seems to be the same issue that you included elsewhere, as my Neg Vote was already registered.
