### ISSUE TITLE
FHIR using different terms than ISO IDMP (administrable vs pharmaceutical product)

### ISSUE THREAD

**Issue by rlindstrm** [hl7-eu/unicom-ig#19]
From Robert Stegwee (robert@trace-health.nl):

In FHIR 5.0.0 the name of the Pharmaceutical Product resource has been changed to AdministrableProductDefinition.

There is no definition for an administrable product in IDMP. The definition of a pharmaceutical product is: "qualitative and quantitative composition of a medicinal product in the dose form approved for administration in line with regulated product information”. Note: Pharmaceutical product and manufactured item are sometimes different when manufactured item(s) are processed before administration to the patient [as the pharmaceutical product].

It does not help when FHIR changes the names of ISO IDMP defined terms, without at least requesting that the IDMP name be changed as well. That is, if there is a convincing reason to actually change the name. Or maybe the resource definition is different from the IDMP definition, which makes life even more complicated.

**Comment by gcangioli** [comment]
My understanding is that the name is different because the AdministrableProductDefinition resource may be used to describe an IDMP PharmaceuticalProduct but not only ...

An AdministrableProductDefinition resource can convey in fact additional details that are beyond the scope of the IDMP PhP

**Comment by rastegwee** [comment]
Thanks for the comment Giorgio. The idea of the IDMP logical model, and hence the definitions, is that they are extensible for specific use cases. See the Deliverable on the Requirements on the Logical Model for IDMP.

Registered as [FHIR-39252](https://jira.hl7.org/browse/FHIR-39252)
No idea how i can add a label R5 ballot, I'm a github newby.

**Comment by Censacrof** [comment]
Hi, just wanted to add that in T6.1, for the FHIR server we are making (using HAPI FHIR library), we mapped the IDMP concept of PharmaceuticalProduct to the FHIR concept of a AdministrableProduct.
