### ISSUE TITLE
AdministrableProductDefinition .property.value[x] should allow ValueString and ValueReference

### ISSUE THREAD

**Issue by cander2** [hl7-eu/unicom-ig#20]
AdministrableProductDefinition.property.value[x] should allow ValueString and ValueReference as possible properties.

Same goes for the ManufacturedItemDefinition.property.value[x]

Use case example, Current approach means we have to add the same image of the product multiple times. If allowed to create a reference, we would have the option to reuse existing images of the product in an ePI by creating a reference to those Binary resources.

**Comment by gcangioli** [comment]
added as https://jira.hl7.org/browse/FHIR-39103 (I've not been able to find it in jira as ballot comment)

**Comment by gcangioli** [comment]
added also https://jira.hl7.org/browse/FHIR-39106
