### ISSUE TITLE
Add a reference from Medication to MedicationKnowledge

### ISSUE THREAD

**Issue by gcangioli** [hl7-eu/unicom-ig#21]
The current model allows the MedicationKnowledge to refer a Medication resource, there are cases however  - e.g. the cross border data exchange - in which it is required to describe the medication by providing a set of additional attributes beside those allowed by the current medication resource.  

Without overloading too much the Medication resource beyond its scope, this need might be fulfilled by enabling the Medication Resource to refer a MedicationKnowledge resource that may convey this additional information (directly or through referred definitional resources)

**Comment by gcangioli** [comment]
added as https://jira.hl7.org/browse/FHIR-38662

**Comment by costateixeira** [comment]
This has been added to FHIR R5. Thank you @gcangioli
