### ISSUE TITLE
Mechanism to bulk import (NCA) data - Document requirements and specs

### ISSUE THREAD

**Issue by costateixeira** [hl7-eu/unicom-ig#28]
We should have a process and tooling to add sample / bulk data from NCAs to FHIR format.
* Support the target resources - Whether this is Medication , MedKnowledge, or Medicinal Product resources, and whether we need or not profiles.
* Support easy update to a new FHIR version when needed
* Support proper, solid governance and work instructions (cannot be one person that knows how it works)
  * CSV may work but with controls around it. 
  * data models may be expected - and overall process / dependencies should be documented

(TBC)

**Comment by rlindstrm** [comment]
Part of issue #47 
Closing this one as a duplicate
