### ISSUE TITLE
IG won't build with CodeSystem url starting with https

### ISSUE THREAD

**Issue by rlindstrm** [hl7-eu/unicom-ig#35]
I have realised that the IG won't build when code system urls have https in it. Which all of EMAs urls have.
I know http is preferred, but https is not forbidden (not that I've checked, but overheard an argument recently). 

So, now that I'm getting back my will to live, what should I do with it? Just pretend EMA IG says http or can you fix it for me somehow? The problem is when I define a CodeSystem, I used https-code systems in profiles and example data without problems.

**Comment by costateixeira** [comment]
I'd push https - it should work.
Want to add a separate branch? If not, commit to the branch you're using
and we'll fix it

**Comment by rlindstrm** [comment]
I don't know. I tried it six times before writing, It seemed clear what the problem was.
Now, that I'm trying to repeat it, it built perfectly with https and dies at http. Clearly, the problem is somewhere else. Probably sitting on my chair.

**Comment by costateixeira** [comment]
It may be a tooling issue so I'm glad to have something broken that I can
fix

**Comment by rlindstrm** [comment]
I found the problem . Wasted nearly two hours to learn what I already knew - I'm just stupid.
