### ISSUE TITLE
debugging help

### ISSUE THREAD

**Issue by rlindstrm** [hl7-eu/unicom-ig#38]
Is there any clever way to debug my fsh files if IG building dies at 'Converting FSH to FHIR' and just stays this way forever?
Obviously I've done something wrong, but I'm all out of ideas.

Sushi: info  Importing FSH text...                                               (00:01.375)
Sushi: info  Preprocessed 13 documents with 28 aliases.                          (00:01.625)
Sushi: info  Imported 22 definitions and 1 instances.                            (00:01.656)
Sushi: warn  SUSHI support for pre-release versions of FHIR is experimental. Use at your own risk! (00:01.661)
Sushi: info  Checking local cache for hl7.fhir.r5.core#5.0.0-ballot...           (00:01.662)
Sushi: info  Found hl7.fhir.r5.core#5.0.0-ballot in local cache.                 (00:02.356)
Sushi: info  Loaded package hl7.fhir.r5.core#5.0.0-ballot                        (00:02.356)
Sushi: info  Found 6 files in input/* resource folders that were neither XML nor JSON. These files were not processed as resources by SUSHI. (00:02.388)
Sushi: info  Converting FSH to FHIR resources...                                 (00:02.395)

**Comment by costateixeira** [comment]
yes. If you are running locally, instead of _genonce, type "sushi ."

**Comment by rlindstrm** [comment]
I had forgotten that. Learned now enough about Powershell execution policies to make it work on the new pc. 
Thank you.
