### ISSUE TITLE
Check why ingredient.for was created in 5.0 - in 4.6. it was the other way around.

### ISSUE THREAD

**Issue by costateixeira** [hl7-eu/unicom-ig#4]

**Comment by costateixeira** [comment]
Ingredient links seems to have been changes due to expected practices and FHIR modeling. However, the way links work doesn't seem to reflect implementation practice, and implementers are apparently using the previous like direction via extension.
This problem could go away while addressing issue #8

**Comment by rlindstrm** [comment]
This is how it went: https://jira.hl7.org/browse/FHIR-31808 
The Jira issue raised and solution provided don't map for me.

**Comment by gcangioli** [comment]
https://jira.hl7.org/browse/FHIR-39139
