### ISSUE TITLE
Capture the Estonian database model 

### ISSUE THREAD

**Issue by costateixeira** [hl7-eu/unicom-ig#41]
there will be a demo

**Comment by rlindstrm** [comment]
The official demo of the Estonian NCA system will take place on 25th of November. [Registration ](https://teams.microsoft.com/registration/74xrybQljk-OESj_8nIBFw,uXVANPE8YECjkOl-9OkRyw,f8Ae4fF3SUi_0rH7VYjB-Q,lRS_XVTAm0ehQ1vo2Lxv4w,Kw1LiZVwWEiDbe9fibQm6Q,pT1rHZDRnkW_KsofkXU8EA?mode=read&tenantId=c96b8cef-25b4-4f8e-8e11-28fff2720117)needed.
I do believe it is aimed at NCAs, so it will cover a lot of the work processes that might not be too interesting for you.

But I can provide you with relevant excerpts from our data model.

**Comment by rlindstrm** [comment]
Medication card (Ravimikaart): includes Medicinal Product, Pharmaceutical Product, Ingredients.
Package (Pakend): includes Package, Manufactured Item.
Value sets (Loendid): includes RMS lists, mappings, attributes
The model is in English, don't be distracted by class names that are parallelly in Estonian.

![medication-card](https://user-images.githubusercontent.com/112903984/201340939-86613b32-5a12-4fda-a579-85b1daf5a2ae.png)
![package](https://user-images.githubusercontent.com/112903984/201340943-1be96438-d83d-40e4-8672-bca34522dc1c.png)
![valuesets](https://user-images.githubusercontent.com/112903984/201340946-f226998a-c8a5-471d-ab43-c723cd515e62.png)

**Comment by Censacrof** [comment]
> The official demo of the Estonian NCA system will take place on 25th of November. [Registration ](https://teams.microsoft.com/registration/74xrybQljk-OESj_8nIBFw,uXVANPE8YECjkOl-9OkRyw,f8Ae4fF3SUi_0rH7VYjB-Q,lRS_XVTAm0ehQ1vo2Lxv4w,Kw1LiZVwWEiDbe9fibQm6Q,pT1rHZDRnkW_KsofkXU8EA?mode=read&tenantId=c96b8cef-25b4-4f8e-8e11-28fff2720117)needed. I do believe it is aimed at NCAs, so it will cover a lot of the work processes that might not be too interesting for you.
> 
> But I can provide you with relevant excerpts from our data model.

Thank you. I registered just in case we will decide to participate. I will need some time to checkout the screenshot that you sent and understand them. 

I think that the restricted IDMP data model that we are using should be part of the specification. I will open an issue for that.

**Comment by costateixeira** [comment]
We need to capture this - in an IG page, or a side wiki page, ...

**Comment by costateixeira** [comment]
Will be in the main branch on a page:
* References
   * National implementations
     * MemberState
        * as many pages as the Member State wants (e.g. EE regulatory DB model)

**Comment by rlindstrm** [comment]
Recording of the [Estonian NCA system demo.](https://youtu.be/eaLhoCuwGQI)  
The solution is open-source and the code will also be available at some point.

**Comment by rlindstrm** [comment]
Can't keep it open forever. And there is still no wiki.
