### ISSUE TITLE
Order of active ingredients

### ISSUE THREAD

**Issue by rlindstrm** [hl7-eu/unicom-ig#43]
Something we're currently struggling with in our national implementation. Maybe a useful warning for you. Maybe you will come up with a wonderful solution. :)

There are no hints about the order of active ingredients in ISO IDMP model or EMA IG or FHIR spec or anywhere else.
However, for medications with multiple active ingredients, users expect to see the main ingredient first and the co-ingredients after. And this should be consistent across products with the same composition, as otherwise it would be difficult to compare them on the screen. Alphabetical order will not help you. For example: over-the-counter paracetamol+codeine product.
![image](https://user-images.githubusercontent.com/112903984/201421443-3b9b053e-42c4-4efc-a535-a95bd902c38b.png)

It should always be Paracetamol 500mg first and Codeine 30mg second. Codeine is an opiate and if it was the main (or significant) ingredient in this product, the product would be something completely different.

This is something to consider when creating the database. However, it's not very straightforward to decide what is first and what is second. You can get an indication of it from the ATC code, but again, it will only help you half way there.

**Comment by costateixeira** [comment]
1. What database? The FHIR server?
2. FHIR exchange persists the order of repeated items. So if we enter
Paracetamol as the first ingredient and Codeine as the second, that will
always be shown as such. Is this something that the users can handle, or do
we need to enforce (especially if it is not easy to decide)?

**Comment by rlindstrm** [comment]
I don't know now, maybe FHIR keeps it in the right order, if you can be sure that it was put there in the right order.

When we have a db and excel sheets and multiple systems, and I guess somewhere there will be a user interface, there will probably be a point where you retrieve the data and it comes in the order randomness, unless you have a way to force the order. 
It's just something to think about and try out. We learned the hard way that this could be a problem. I wanted to share. :)

**Comment by Censacrof** [comment]
If had to guess, from a chemical composition point of view order does not matter. Maybe this is why IDMP doesn't take care of it. Also, if you think about it, most of the time that information will be directly inside the fullName of the MedicinalProduct, so maybe we don't really need it elsewhere.

**Comment by rlindstrm** [comment]
Full name includes strength and dose form, not substance.
I agree, it mostly matters in the UI. But the problem is, that you cannot fix it within the UI. 
Possibly not relevant for this project. :)

**Comment by rlindstrm** [comment]
Covered in the UNICOM IG Known Issues section
