### ISSUE TITLE
Define common examples for end-to-end

### ISSUE THREAD

**Issue by costateixeira** [hl7-eu/unicom-ig#45]
For UNICOM teams to be able to develop their apps with a common goal, we need to have a set of common examples that are used across the entire specification.

If we look at regulatory DBs with all their complexity but if the prescription/dispense is only working for Paracetamol, this is not a fair and thorough design validation. But if we want to make examples for all the PPL, we won't do anything else.

We must ensure that the same data that comes from the NCAs will be usable in the clinical flows.
Suggest to use one product for each of these:  
* Amlodipine (simple but with different salts)
* Paracetamol (because everyone should have paracetamol)
* Qlaira (because it's complicated and exists most everywhere and it should be easy to make a scenario)
* some cream for "uncertain" doses?
* a mixed product where ingredients of the manufactured item and of the pharmaceutical product are different
* ..?

**Comment by costateixeira** [comment]
Check which ones exist in UFIS and use those.

**Comment by rlindstrm** [comment]
Some examples (all in UFIS, some are already available in [Implementation Guide](https://build.fhir.org/ig/hl7-eu/unicom-ig/branches/mpd-r5/artifacts.html#example-example-instances), some are in the to do list).
Happy to discuss, change/add products or information.

**1.	Cefuroxime sodium 1500mg/vial powder for solution for injection/infusion.**
 a.	Medium complicated package (1/5/10 vials in one package, size of vial not specified)
 b.	Dose form tranformation before administration (powder -> solution); solvent not included in package.
 c.	Reference strength
 d.	Two routes of administration
 e.	Some products have strength 1500mg, others 1.5g.
 f.	Available by different brands and different countries.
 g.	[Example EE](https://idmp-viewer.azurewebsites.net/display-product?url=http://ppl02.azurewebsites.net/MedicinalProductDefinition/Cefuroxime-MIP-1500mg-powder-for-solution-inj-inf-EE-MPD), [Example SE](https://idmp-viewer.azurewebsites.net/display-product?url=http://ppl02.azurewebsites.net/MedicinalProductDefinition/Zinacef-1.5g-Powder-SE-IS-MedicinalProductDefinition)

**2.	Clotrimazole creme and pessaries/tablets** (Canifug Cremolum / Canesten / Canesten Combi)
 a.	Combination package (creme + pessaries, creme + tablets)
 b.	Two pharmaceutical/administrable products
 c.	Combined dose form as authorised dose form
 d.	Something like this available in all countries, but with variations
 e.	[Example EE](https://nprogram.azurewebsites.net/display-product?url=http://ppl02.azurewebsites.net/MedicinalProductDefinition/CanifugCremolum-100mg-10mg1g-Cream-Pessary-EE-MPD)

**3.	Ethinylestradiol 0,02 mg/ drospirenone 3 mg tablets**
 a.	Many products in all countries
 b.	Some products with placebo pills (pack size challenge, two different manufactured items in one blister)
 c.	Reference strength
 d.	Strength sometimes in micrograms, sometimes in mg
 e.	Examples SE [with 4 placebos](https://idmp-viewer.azurewebsites.net/display-product?url=http://ppl02.azurewebsites.net/MedicinalProductDefinition/Yaz-0023mg-tablet-SE-AJ-MedicinalProductDefinition), [with 8 placebos](https://idmp-viewer.azurewebsites.net/display-product?url=http://ppl02.azurewebsites.net/MedicinalProductDefinition/Yasminelle28-tablet-SE-AJ-MedicinalProductDefinition), [no placebos](https://idmp-viewer.azurewebsites.net/display-product?url=http://ppl02.azurewebsites.net/MedicinalProductDefinition/Yasminelle-tablet-SE-AJ-MedicinalProductDefinition), etc

**4.	Amlodipine 5mg and 10mg tablets**
 a.	Simple package, simple dose form, many products
 b.	Substitution rules can be tested between pack sizes and strengths
 c.	Reference strength
 d.	Seemingly identical packages with different PCIDs (only blister material different)
 e.	EE examples: [5mg](https://idmp-viewer.azurewebsites.net/display-product?url=http://ppl02.azurewebsites.net/MedicinalProductDefinition/Agen-5mg-Tablet-EE-MPD) and [10mg](https://idmp-viewer.azurewebsites.net/display-product?url=http://ppl02.azurewebsites.net/MedicinalProductDefinition/Agen-10mg-Tablet-EE-MPD); SE examples:  [5mg](https://idmp-viewer.azurewebsites.net/display-product?url=http://ppl02.azurewebsites.net/MedicinalProductDefinition/AMLaccord-5mg-Tablet-SE-IS-MedicinalProductDefinition), [10mg](https://idmp-viewer.azurewebsites.net/display-product?url=http://ppl02.azurewebsites.net/MedicinalProductDefinition/AMLaccord-10mg-Tablet-SE-IS-MedicinalProductDefinition); etc 

![image](https://user-images.githubusercontent.com/112903984/202697018-a660f45a-345e-46f6-8bab-85616cc61532.png)

We also have the nightmare called [Qlaira](https://idmp-viewer.azurewebsites.net/display-product?url=http://ppl02.azurewebsites.net/MedicinalProductDefinition/Qlaira-Film-coated-tablet-EE-MPD), which is good for testing your data model, but it’s not technically a PPL product. It has 5 different kind of tablets in one blister (including placebo), and there is a challenge to understand which of the ingredients would be ok to share and which not.
