### ISSUE TITLE
Make the bridge to NCA data inclusion

### ISSUE THREAD

**Issue by costateixeira** [hl7-eu/unicom-ig#47]
For NCAs to be able to use the work and to enter the data which is important for UNICOM, there must be a set of solutions, procedures to enable NCAs (besides the communication and awareness which is most important).
We should have a framework for how NCA data can be added - with an agreed functionality and scope, so that the adequate tooling and processes can be designed.

**Comment by costateixeira** [comment]
This should also capture the plan to show our external stakeholders that even if we have local/temporary solutions, they are not impeding the overall solution.

**Comment by rlindstrm** [comment]
Working process exists. 
https://github.com/unicom-project-eu/unicom-tools
