### ISSUE TITLE
Convert fhir bundles from xml to fsh

### ISSUE THREAD

**Issue by rlindstrm** [hl7-eu/unicom-ig#48]
I need to convert a bunch of XMLs to FSH for the implementation guide. 
All our full medication examples are currently in xml, but to handle the version changes and some attribute or code system name changes, it would be much better to have them as fsh.
Advice/help appreciated.

**Comment by Censacrof** [comment]
I can help you with that. Can you please share some examples of what you would like to convert?

**Comment by costateixeira** [comment]
I think the idea is to document this so that Rutt as well as others can do
this.

Generally, the options are:
0. Ensure the XML is valid (if needed, using some XMLLint).
1. Convert XML to JSON (using the FHIR validator , needs to be documented
more )
java -jar validator_cli.jar "XXXX.xml" -version 4.3.0 -output "XXXX.json"
2. Convert JSON to FSH using GoFSH (need to document how, esp, the GoFSH
options)
3. Clean up FSH

Alternatively to 1, you can POST to a server, and get the JSON

**Comment by rlindstrm** [comment]
> I think the idea is to document this so that Rutt as well as others can do this.

"The idea"... Whose idea?
My idea was to post the problem and get someone do stuff for me.

**Comment by costateixeira** [comment]
I correct myself:

Let's take this opportunity not to give Rutt a FSH, but to give her the
tools so that she can FSH.

**Comment by Censacrof** [comment]
@costateixeira my original intention was (and still is) to create a tool able to do that automatically

**Comment by joofio** [comment]
I have already done similar work with a small script that I can share. Uses the java validator as Jose mentioned

**Comment by Censacrof** [comment]
Hi @joofio, pleased to meet you. I think if you shared that script it could be helpful

**Comment by joofio** [comment]
I will change the code to suit this case (the original is the other way around) and post it ASAP

**Comment by joofio** [comment]
this snippet should be enough for this purpose with goFSH:
https://gist.github.com/joofio/8eeb8586005c4eed8082e630af02d559 

for the opposite (fsh to XML) this code over here with sushi: 
https://gist.github.com/joofio/c9b04b6e8dfa9a0a876526f724933cce

**Comment by costateixeira** [comment]
@joofio how do you think we can document these auxilliary tools? I think they are useful and should not be lost in a backlog.
@rlindstrm did this help? Can we close this issue if it works and is documented?

**Comment by joofio** [comment]
@costateixeira we can add a folder of something like "utils"? and add the scripts? properly documented of course, like the branch allocation discussed early today

**Comment by Censacrof** [comment]
> @costateixeira we can add a folder of something like "utils"? and add the scripts? properly documented of course, like the branch allocation discussed early today

I agree, we should create a wiki in this repo to use as our knowledge-base.

**Comment by costateixeira** [comment]
add to https://github.com/hl7-eu/unicom-ig/tree/master/tooling
?
(Suggestion: when Rutt confirms this is useful/working, we can make a PR,
quoting this issue #48, and adding a readme in that folder for
documentation)

**Comment by costateixeira** [comment]
Wiki is fine, linking to the different files in the repo. (I'd still have a
readme)

**Comment by joofio** [comment]
not needed anymore. reopen if needed
