### ISSUE TITLE
Migrate UFIS data to IG/server

### ISSUE THREAD

**Issue by costateixeira** [hl7-eu/unicom-ig#49]
The goal is to capture specifications and data, and separate those from the actual instance of the server.

* Capture lessons learned
* See what to do with the existing data
* Decide how to get more data (given the lessons learned)
* Migration architecture for short-term (eHN)

**Comment by rlindstrm** [comment]
Extracted data in https://github.com/unicom-project-eu/source-data/tree/main/ufis/extracted

We migrate examples with textual id-s. The ones with guids were first examples, and were remade later with new IDs.
The ones that have already been migrated (see IG examples), should be excluded.

**Comment by rlindstrm** [comment]
Done, see UNICOM Toolbox
