### ISSUE TITLE
Add issues and decide due date for Milestone v0.1.0

### ISSUE THREAD

**Issue by Censacrof** [hl7-eu/unicom-ig#50]
I have just created the Milestone v0.1.0 so that we can plan our first release and the features that it will have.

We need to do 2 things:
1. Define our expectations for this release and decide which issues to add to the milestone (maybe create new ones).
2. Decide the due date. For the moment I have set it to the 16th of December, because to me it seems a reasonable date, of course it is something we need to discuss together.

Also, as said in issue #31, we should really define our release cycle. 

One of the reasons that I created the milestone is that the unicom-ig has become a dependency for WP6, WP8 and probably more. In order to plan our activities we need to know the date of the first release of this specification.

**Comment by costateixeira** [comment]
Thanks. I think we should either decide due dates or scope. Not both.
I would plan this differently - let's see which parts are actually critical
- and from those parts, decide the minimum scope. Then we plan dates.

With this project I would not make assumptions that the requirements are
clear and we know the scope.

**Comment by rlindstrm** [comment]
If you don't specify the scope, you can set the due date to today. :)

But more seriously, is this milestone a boys' thing or is there something you expect me to achieve, as well?

**Comment by Censacrof** [comment]
> If you don't specify the scope, you can set the due date to today. :)
> 
> But more seriously, is this milestone a boys' thing or is there something you expect me to achieve, as well?

@rlindstrm of course it's not a boys' thing, it regards everybody in the UNICOM project. A Milestone is basically a collection of Issues with a due date attached, we use it to plan what to add / fix before the next release of the unicom-ig.

I would like you, as anyone contributing to this repository, to participate in the decision about scope and due date of the release.

I propose that we start by adding issues to the milestones and in the first half of the technical meeting next week, we decide which issues to remove from the milestone, which to add, and create new ones if needed. In the second half of the meeting we can decide the due date.
