### ISSUE TITLE
Consolidate and document approach for externally defined code systems

### ISSUE THREAD

**Issue by costateixeira** [hl7-eu/unicom-ig#53]
Namely for EMA code systems, we need an approach that is clear, documented and validated across other WPs. We may choose a temporary solution only for validating the resources and support profiles, without waiting for an EMA FHIR IG.
@gcangioli suggested to look into the different options, this issue captures such a need. 
At the closure of this issue we should have the approach documented in the IG, checked with WP1 and applied to the resources that need it.

**Comment by RobertVanderStichele** [comment]
What we need for the EDQM terminologies is correspondance lists between EDQM coding of PDFs (and ADFs), and language mappings. 
All this can be exported from the EDQM website on standard terms, but the question is in what kind of resource we will store it, locally, for use in UNICOM by persons and people that do not have access to SPOR (not belonging to an NCA). 

EDQM has a limited but steady updating cycle.  That needs to be taken into acount. 

There is an ISO standard for multilingual terminologie (TMF). Should that be an intermediate resource before sending data to FHIR resources ? 

The following standard term types need to be considered: 

Dose forms, routes of administration, unit of presentation, container. 


The question of the coding systems for substance (EU-SRS, via SMS, and SPOR) is best discussed in another issue. 

UCUM is not under EMA. We should provide it also a resources. 

bob

**Comment by rlindstrm** [comment]
EMA SPOR lists have been added to the IG. 
For SMS, just the PPL substances (and related modified substances), because otherwise we'd need to keep a list of 50 000 concepts in the IG and it makes things slow).
