### ISSUE TITLE
Add "implementation issues / faqs" page to regulatory IG

### ISSUE THREAD

**Issue by costateixeira** [hl7-eu/unicom-ig#59]
The implementation guide from UNICOM should reveal the lessons that are important for implementers adopting IDMP and EMA guidance.

For example: not having reference strength type, or that the PCID is dependent on the package material, which might cause confusion in a system that doesn't have information about package materials

For now, this could be a narrative page

**Comment by rlindstrm** [comment]
https://build.fhir.org/ig/hl7-eu/unicom-ig/branches/mpd-r4b/issues.html

**Comment by rlindstrm** [comment]
José added the [page](https://build.fhir.org/ig/hl7-eu/unicom-ig/branches/mpd-r4b/issues.html), I filled it with initial content. There is room to improve, but I would be happy if others (@Censacrof, @joofio) in the project read it and gave feedback if it made sense to them or if they would like to see something else there.
