### ISSUE TITLE
Add a device - just the device type

### ISSUE THREAD

**Issue by costateixeira** [hl7-eu/unicom-ig#6]

**Comment by rlindstrm** [comment]
To include information about a simple device inside the package PackagedProductDefinition.packaging.containedItem with DeviceDefinition should be used. Worth a discussion.

![image](https://user-images.githubusercontent.com/112903984/194480483-adb849cd-a634-490b-8b62-cfaf05b4b857.png)

This implies that all devices should be created as separate resources, which is compliant with the marketing authorisation application process, but is in most cases completely unnecessary in later stages of the product life cycle. We do not typically want to define a device, but simply indicate a type of device (an applicator, a measuring cup, a spoon). 

A simple coded value set (administration devices from EDQM packaging value set, for example) and an appropriate attribute in PackedProductDefinition would be enough for most cases.

**Comment by gcangioli** [comment]
It is a codeableRefernce so you are not obliged to add a DeviceDefiniton a code could be enough.

**Comment by costateixeira** [comment]
Discussion:
* CodeableConcept lacks the indication that the containedItem is a device or a product or a package.
* Refrence requires another resource
* Logical reference could help but does limit searching capabilities
