### ISSUE TITLE
Inventory of existing data

### ISSUE THREAD

**Issue by costateixeira** [hl7-eu/unicom-ig#61]
* Estonia can provide more data if useful
  * HL7EU/João can support with the tooling as needed
* Useful for Task 6.6
* Countries that have data
  * Estonia - OK in repo (from UFIS)
  * Sweden - 
  * Norway - 
  * Italy - 
  * Finland - 
  * Belgium - 
  * Greece - 
  * US - 
  * Portugal - 
  * Netherlands have shown interest

* What is its status?

We agree that Rutt will establish the contact with the NCAs. The data collected will be handed over to the repository. We will provide an overview of that data as is.

**Comment by rlindstrm** [comment]
Narrative overview is happening [here](https://github.com/unicom-project-eu/source-data/wiki/Overview).
It's work in progress.

**Comment by rlindstrm** [comment]
At this point WP8 excel sheets for 4 substances are not finalised, but we have general [overview ](https://github.com/unicom-project-eu/source-data/wiki/Overview)of what we have, and a plan to go ahead. The page in the link will be occasionally updated to keep track. 
Results, as vague as they are, reported to Farah and WP4.
