### ISSUE TITLE
EDQM-SPOR mappings

### ISSUE THREAD

**Issue by rlindstrm** [hl7-eu/unicom-ig#64]
I have a set of code systems based on EMA SPOR:  https://github.com/hl7-eu/unicom-ig/tree/mpd-r4b/input/fsh/codesystems
My approach was simplistic, I did not include attributes for dose forms or different languages. Not sure if they're needed in both code systems.

Francesco is working on EDQM value sets in a more sophisticated manner.  I don't know if it's going to be a problem, that EDQM is considered one code system with many value sets, but all EMA SPOR lists are considered different code systems.

We need concept maps between EDQM and EMA SPOR.

**Comment by rlindstrm** [comment]
I've used [Ontoserver Snapper ](https://ontoserver.csiro.au/snapper/) for creating FHIR terminology (code systems or concept maps) from CSVs. I'm sure there are other ways, so just saying.

**Comment by G-DPP** [comment]
Me and @Censacrof noticed that the SPOR has not a 1-to-1 correspondence with EDQM. For example the source id of "Powder for mouth wash" in Combined Pharmaceutical Dose Form is not defined, that means the code does not exists in EDQM. Is it possible to exclude from the mapping all the code that are in the SPOR but not in EDQM?

**Comment by rlindstrm** [comment]
"Powder for mouth wash" seems to have Term Status "Nullified" in SPOR. I'm almost sure it means it is not in active use anymore and can be safely ignored.
If it's not too much trouble for you, you can create a list of those that don't have a mapping, so that I could check if there's anything problematic. You can always ignore everything that is marked non-current or nullified in SPOR.

**Comment by joofio** [comment]
from today meeting: https://github.com/unicom-project-eu/wp6-NCPeH-substitution/blob/main/Substitution_R4B/data/SPOR_EDQM.json

**Comment by rlindstrm** [comment]
I have successfully (?) created a SPOR dose forms CodeSystem with extra property for EDQM codes, and a ConceptMap from EDQM to SPOR dose forms.
I will try to get them uploaded to the IG when I'm at the right computer. 
If either one or both those approaches are ok, I can do the rest.

**Comment by rlindstrm** [comment]
1) The first SPOR code system with EDQM mappings in properties is uploaded, [please enjoy Pharmaceutical Dose Forms here](https://build.fhir.org/ig/hl7-eu/unicom-ig/branches/mpd-r5/CodeSystem-pharmaceutical-dose-form-ema-cs.html).

2) EDQM -> EMA ConceptMap as a resource has a problem. It looks like IG publisher is looking for source codes (EDQM), but we don't have them published as a CodeSystem in our IG, and they're not available publicly either. The error goes: 

_java.lang.NullPointerException: Cannot invoke "String.equals(Object)" because the return value of "org.hl7.fhir.r5.model.ConceptMap$SourceElementComponent.getCode()" is null_

The concept map is commented out for now but available in the repo for anyone who wants to investigate. Also, be aware, that the concept map was created with an R4 tool and manually altered to work for R5. There could be something I did not spot.

**Comment by rlindstrm** [comment]
2. is also fixed now. See our first concept map here https://build.fhir.org/ig/hl7-eu/unicom-ig/branches/mpd-r5/artifacts.html#terminology-concept-maps 

Feel free to give feedback to both approaches. Or see me lose my motivation.
