### ISSUE TITLE
EMA ATC code system & mapping to WHO ATC

### ISSUE THREAD

**Issue by rlindstrm** [hl7-eu/unicom-ig#65]
We have WHO ATC.
EMA SPOR has ATC code system with their own RMS codes. It is not clear if the display label should be ATC code or the name.

Create EMA SPOR code system and value set for ATC.
Create concept map between EMA and WHO ATC.
Document possible problems and questions along the way.

@Censacrof is this to you as well? I have not done EMA ATC myself yet. Giorgio did WHO ATC.

**Comment by Censacrof** [comment]
@rlindstrm I think ATC were assigned to @gcangioli . I can help, but first I would like to close my assigned Issues.
