### ISSUE TITLE
Data from Estonia - trial idmp-transformation for amlodipine

### ISSUE THREAD

**Issue by rlindstrm** [hl7-eu/unicom-ig#67]
This an attempt to create a tool/workflow for taking AS IS data and turn it into FHIR/IDMP resources. 
Assigned to Joao, but feel free to unassign for now if you have better things to do. It's just to test how well this approach works.

Export from EE new information system (from UI).
[EE-Amlodipine.zip](https://github.com/hl7-eu/unicom-ig/files/10155449/EE-Amlodipine.zip)

Some things to notice:
-	A lot of the data is repeated on the medicinal product level and the package level. Marketing authorisation in Estonia is always on medicinal product level, others are probably easier to figure out.
-	MPID in our example data has been EE-[number from LOC-ID]-[Medication card number]
-	PCID in our example data has been MPID-[package number]. In our example data we have different PCIDs if the same package has two different options for material, but I think this might not be readable from these files.
-	It looks like it’s all text, but actually everything is coded, but we only see display labels. I included SPOR RMS lists from our local system to do the reverse-coding by text. Most of these value sets are present in my IG as well. These list IDs are used as variables for the code system in my fsh files. 
-	ATC is only displayed as WHO code. My IG expects SPOR code (again, technically doable)
-	A lot of the data is fixed or default in the profiles, also country and language for EE products are always fixed.
-	Be aware of the order of the ingredients. There is no numbered order for them and they sort of come up as quickly as they get there from the database. It might happen, that sometimes they are one way, sometimes the other way. Somewhere in the UI the ingredients and strengths didn’t match, but at first glance it looked like this output is ok.
-	Strength units should all be from SPOR.

**Comment by rlindstrm** [comment]
First draft: https://github.com/joofio/pplCreator/tree/main/ee-PPLCreator 

**Medicinal Product Definition:**
- IS * domain = http://hl7.org/fhir/medicinal-product-domain#100000000012 "Human use"
- SHOULD BE * domain = $100000000004#100000000012 "Human use"  

- IS * status.coding[0] = $200000005003#Valid "Valid"
- SHOULD BE * status.coding[0] = $200000005003#200000005004 "Current" (or whatever else we agree for statuses)  

- IS * classification[atc].coding[who] = $who-atc##C09DX01 "C09DX01"
- SHOULD BE * classification[atc].coding[who] = $who-atc##C09DX01 "valsartan, amlodipine and hydrochlorothiazide "
- ADD * classification[atc].coding[ema] = $100000093533#see the SPOR list provided: source columnG, target columnA; display name can be the same as the WHO ATC one.

- IS * name.productName = "COPALIA HCT 160mg, 12.5mg, 10mg Õhukese polümeerikattega tablett"
- THIS IS FOR ME TO THINK

**Administrable Product Definition**  
- Unit of Presentation missing. It is present in ManufacturedItemDefinition and seems to be correct there. 
  
**Manufactured Item Definition**
- remove manufacturer (in data, there is only marketing authorisation holder, but that's another resource)

**Ingredient**
- reference strength and presentation strength are the same, but there is not much we can do about it

- IS * for[0] = Reference(mpCOPALIAHCT) 
- SHOULD BE references to manufactured item and administrable product as well. (Good thing is that medicinal products seem to have all the ingredients they need.)

**Packaged Product Definition**
- IS * identifier[pcid].value = "MPID-1714384"
- SHOULD have MPID value instead of "MPID". So it should look like EE-100002580-15548-1109900.  

- REMOVE manufacturer

- outer package should always be box with quantity 1.
- package type given in the file is inner package (quantity usually 1 or not specified, as we don't know the number of blisters)
-  ADD reference to manufactured item as package.package.containedItem.item.reference
- number of tablets (=manufactured items) in the inner package is in   package.package.containedItem.amount.value

**Regulated Authorisation**
- identifier system needs discussion. Currently they all use the same system (defined in the IG), but it may cause identifier collisions between national authorisations from different countries.
- all looks correct

**Organisation**
- Add  identifier[org].value (currently given in id, but I would suggest having it as identifier. We might need this information to be in the same place for all data at some point)

So I think the name of the precise ingredient (salt) and its strength is the only issue we cannot solve by automation. Everything else should be more or less doable. Pretty amazing.
SPOR value sets that I have in the IG don't have Estonian display names, so all of those would give an error when validated with the strict profiles.

**Comment by rlindstrm** [comment]
Used the visualiser to find more issues (most of those that are listed above are also still there):

ManufacturedItem is not referenced from PackagedProductDefinition, so manufactured item never shows up in the data.

Ingredient has only references to MedicinalProductDefinition, but not to AdministrableProductDefinition or ManufacturedItemDefinition.

**Comment by rlindstrm** [comment]
And some notes to myself:
Rules for creating full name:  * name.productName = "COPALIA HCT 160mg, 12.5mg, 10mg Õhukese polümeerikattega tablett"
Local ATC code is used. Need to map to international ATC.

**Comment by joofio** [comment]
Issues: (will Update as I correct them)

**Medicinal Product Definition:**
- [x] domain
- [ ] status.coding
- [x] classification[atc].coding[who]
- [ ] classification[atc].coding[ema]

**Administrable Product Definition**
- [x] unitOfPresentation 

**Manufactured Item Definition**
- [x] remove manufacturer

**Ingredient**
- [x] add references to manufactured item and administrable product 

**Packaged Product Definition**
- [x] remove manufacturer
- [ ]  indentifier
- [ ] outerpackage as box
- [ ] reference to manufaturedItem
- [ ] number of tablets


**Organisation**
- [x] identifier [org]

**Comment by rlindstrm** [comment]
> [ ] outerpackage as box (will this work for every drug?)

I was quite sure there was a rule for it in the EMA IG or one of the supporting materials, but I can't find it now. 

Even if there wasn't, it's usually true, and it is a valid migration rule in Estonian database, so all the packages that came from the old db have the outer package type 100000073498 "Box".

**Comment by rlindstrm** [comment]
I found a problem that I thought was caused by multiple ingredients, but actually it might be coming from the naming system of manufactured item. I guess you know better.

The symptoms are:
http://fhir.hl7.pt/fhir/ManufacturedItemDefinition/mid-dafirohct ([see in visualiser](https://idmp-viewer.azurewebsites.net/display-product?url=http://fhir.hl7.pt/fhir/ManufacturedItemDefinition/mid-dafirohct))
This manufactured item has 6 ingredients, clearly duplicates, but with different strengths.
That appears to be caused by the medicinal product having the same name for two products, which actually have different strengths: 
[DAFIRO HCT 10mg, 12.5mg, 160mg](https://idmp-viewer.azurewebsites.net/display-product?url=http://fhir.hl7.pt/fhir/MedicinalProductDefinition/mp-48e9dc9be347304877f019cdb587cb6f)
[DAFIRO HCT 25mg, 5mg, 160mg](https://idmp-viewer.azurewebsites.net/display-product?url=http://fhir.hl7.pt/fhir/MedicinalProductDefinition/mp-60519618dfee43c919c39ed35a78bd3c)
[DAFIRO HCT 25mg, 10mg, 320mg](https://idmp-viewer.azurewebsites.net/display-product?url=http://fhir.hl7.pt/fhir/MedicinalProductDefinition/mp-1d58916b8dd3a00bafe27af1e3fb67db)
None of the above seem to have the correct MID linked to them, so the ingredients info doesn't show.

But the MID and a selection of ingredients come up here instead:
[DAFIRO HCT 25mg, 160mg, 10mg](https://idmp-viewer.azurewebsites.net/display-product?url=http://fhir.hl7.pt/fhir/MedicinalProductDefinition/mp-25b4fc8e45300bba6eff5ef9106d2efd)

It is a complicated case and not too relevant for PPL data at this point. I would suggest to do the next round with single ingredient products to get at least some data working. When the viable minimum is achieved, we can move on to fixing more complicated cases.

**Comment by joofio** [comment]
I believe I have now corrected that issue as well. Your analysis was correct. it was about the naming of the resources.

**Comment by rlindstrm** [comment]
Looks pretty :)
Just a few remarks:
1) Is it a consequence of something that there is only one package per medicinal product or is it your intentional choice for now?

2) As the final step, I would expect the display names for codes to be in English.

3)  EMA ATC is still using WHO code instead of SPOR RMS code. 
Now, below is a picture of the same ATC file I sent you. 
For amlodipine there is RMS code in column A and this would be the right code for EMA ATC code. 
* classification[atc].coding[who] = $who-atc#C08CA01 "amlodipiin"
* classification[atc].coding[ema] =  $100000093533#**100000095065** "amlodipine" 

But Estonian ATC list is more granular than official ATC, so you will find many cases where Column A says "puudub", which means that there is no specific RMS code for this term (and the Estonian ATC is in column L. 
For cases like this, it would be correct to use the Parent RMS code (column G).
* classification[atc].coding[who] = $who-atc#**C08GA02 "amlodipine and diuretics"**
* classification[atc].coding[ema] = $100000093533#**100000157855 "amlodipine and diuretics"**

![image](https://user-images.githubusercontent.com/112903984/210278172-ef284a68-7d66-4040-b621-98f13dbc7d13.png)

4) The most isignificant thing of all. If it's easy enough, change following:
- strength part of the name: in case of multiple ingredients, use slash instead of comma, like 1,5 mg / 5 mg 
- dose form part of the name should start with lower case letter (and usually be in plural, but it's too early to start learning Estonian grammar)

**Comment by rlindstrm** [comment]
Hi,

Can you run your scripts with these products: https://github.com/unicom-project-eu/source-data/tree/main/Data%20As%20Is/EST  

Amlodipine-only products from Estonia. They are all the same atc and substance. Please note the reference strength and strength columns, which I've painted colourful - I think the template uses another column for strength data, but this is better.

**Comment by joofio** [comment]
https://github.com/joofio/pplCreator/tree/r5/input/fsh/ee2/amlodipine-medicinalproduct-automatic

**Comment by rlindstrm** [comment]
Note to me: next time, have MA status date in the Packages file.

**Comment by rlindstrm** [comment]
Note to @joofio : Please upload to the server so I could use the visualiser. :)

**Comment by rlindstrm** [comment]
Import scripts finalised for simple products. Closing this issue, because it was the trial batch of amlodipines, and it's done. 

Here's an example: https://jpa.unicom.datawizard.it/apps/visualiser/index.html?url=https://jpa.unicom.datawizard.it/fhir/MedicinalProductDefinition/mp-17aa3bb6faec404ef2e078cb38f6d778
