### ISSUE TITLE
Relaxed profiles for as-is data

### ISSUE THREAD

**Issue by rlindstrm** [hl7-eu/unicom-ig#69]
Current profiles are too strict to process partial or incomplete data.
To improve importing functions for as-is data, we should have a set of profiles that conform to the strict profiles, but without forcing cardinalities or EMA SPOR  terminology bindings.

1) Agree on relaxation techniques
2) Decide terminology bindings (if any)
3) Do the profiles (examples should work for both)
4) Make strict profiles dependant on relaxed ones to ensure the consistency.

**Comment by RobertVanderStichele** [comment]
Coordination with the "data AS IS" approach, advocated by me, and based on an excell file with common structure, compatible with T6.1 is needed.

**Comment by costateixeira** [comment]
Rutt should handle the requirements and all the compatibility for that. The compatibility with T6.1 should be ensured with the technical approach suggested recently.

**Comment by rlindstrm** [comment]
Yes, the aim of these 'relaxed profiles' is to work with Robert's Excels (as well as any others) and get them imported to db 6.1. 
I should have explained that connection better in the original issue.

**Comment by rlindstrm** [comment]
I created relaxed profiles in mpd-r4b branch. Removed as many mandatory elements as possible, removed terminology bindings. The bindings and code systems needed by the strict profiles are in comments to make it easier to follow. 
Still looks a little messy. QA far from clean, but I don't understand the problem there. 

Strict profiles don't derive from the relaxed ones yet (one test profile only). I would like to discuss that again with someone. Examples seem to work with relaxed profiles as well.

@joofio I guess they are mostly for you to use, so feel free to change or disregard or whatever you need to do. I just tried to guess what would be useful. :)

**Comment by rlindstrm** [comment]
So this was the commit that I asked to be removed. I will re-commit the relaxed profiles when the IG is fixed.
I would still like to discuss some of the logic.

**Comment by rlindstrm** [comment]
The relaxed profiles are now back in mpd-r4b branch ([here](https://build.fhir.org/ig/hl7-eu/unicom-ig/branches/mpd-r4b/artifacts.html#data-transformation-profiles)).

I merged changes from Giorgio's branch manually, and made some of my own changes on top of that.
Strict profiles don't derive from the relaxed ones. Not difficult to make them do that, but I need some bugs fixed first.

Feedback is welcome.

**Comment by costateixeira** [comment]
Done. We'll add dependencies if/when needed
