### ISSUE TITLE
Concentration and Presentation Strength

### ISSUE THREAD

**Issue by costateixeira** [hl7-eu/unicom-ig#7]

**Comment by costateixeira** [comment]
Inlcuding how to handle Reference Strength

**Comment by rlindstrm** [comment]
Strength issue in [Ingredient resource](http://hl7.org/fhir/2022Sep/ingredient.html) consists of several problems:
**1) Ingredient.substance.strength 0..***
What would be the use case for several strengths per one substance, given that the strength explicitly includes concentration, presentation and multiple reference strengths?
![image](https://user-images.githubusercontent.com/112903984/194475102-ab8494c2-b3cc-4e88-9422-750e30c7efc0.png)

It is the same in IDMP, with the exception that reference strength is under strength, not next to it like in FHIR:
![image](https://user-images.githubusercontent.com/112903984/194475416-69155fa4-7d8e-492d-84e8-80c4e674e5d3.png)

**Comment by rlindstrm** [comment]
**2) Concentration and Presentation Strength**

![image](https://user-images.githubusercontent.com/112903984/194476525-5d656c17-4a26-4f78-b986-7ba3366ef341.png)
Concentration Strength and Presentation Strength are identical in Ingredient resource. They could be the same attribute, made distinct by strength type, or maybe this distinction is not relevant at all as it doesn’t really give any extra information.
For example, inside ReferenceStrength, this kind of distinction is not made and nobody misses it.

**Comment by rlindstrm** [comment]
There is no way of saying whether the substance in the reference strength provided is basis of strength or active moiety. EMA implementation does not require that, but certain countries (Sweden, for example) make a clear distinction and they may have two different reference strengths for one product. It should be discussed whether it needs to be added or not.

There is an attribute strength.basis which is logically connected to this problem, but doesn’t actually give any information as it’s not in the reference strength section and only says whether the strength provided is per substance base or salt (information which should be clear from the name of the substance).

![image](https://user-images.githubusercontent.com/112903984/194477591-036dc237-1c4c-4192-8aa2-0e34c2f5579e.png)

**Comment by costateixeira** [comment]
Possible proposals (to be validated)
Currently we have strength 0..* and inside we have reference strength
At this moment it is difficult to understand if the reference strength is for presentation or concentration, unless we have to look at the data - in which case we may as well make for RefStrength the same distinction as we do for strength.

So, to fix this, we could either :
* Add narrative to explain how it is supposed to work
* Add a constraint that strength can be either presentation or concentration (each of them can contain a referenceStrength(
* Remove presentation[x] and contraction[x], and use a strengthType (presentation or concentration) in a repeatable element

**Comment by gcangioli** [comment]
https://jira.hl7.org/browse/FHIR-39134
