### ISSUE TITLE
Fix the IG home page

### ISSUE THREAD

**Issue by rlindstrm** [hl7-eu/unicom-ig#70]
Merging branches made the IG home page go weird.
The mpd-r4b branch IG [link ](https://build.fhir.org/ig/hl7-eu/unicom-ig/branches/mpd-r4b/index.html) is in some of the deliverables that are circulating. 
Please fix it or help me fix it at least for my branch, as it does not look good to have a broken landing page.

**Comment by Censacrof** [comment]
I just took a quick look at the source of the page and there is something weird going on:

![image](https://user-images.githubusercontent.com/15619279/207638911-d8523e2f-a218-46f4-96c0-2bad169ea716.png)

If you are familiar with HTML you know that those are not valid HTML tags. To me looks as if some kind of HTML pre-processor (I can't tell which one) failed, or wasn't run at all.

**Comment by rlindstrm** [comment]
I created a [new page](https://build.fhir.org/ig/hl7-eu/unicom-ig/branches/mpd-r4b/regulatory.html) in the IG for regulatory data use case (branch mpd-r4b). Most of what I had on the UNICOM IG home page was transferred there, so now the home page is more or less empty.
Once the home page is fixed, we can give it new and more broader content.

**Comment by costateixeira** [comment]
see discussion here
https://chat.fhir.org/#narrow/stream/179252-IG-creation/topic/Formatting.20Errors.20-.20Sushi.20and.20Latest.20Publisher

**Comment by rlindstrm** [comment]
This is fixed.
