### ISSUE TITLE
Usage of the value set binding 

### ISSUE THREAD

**Issue by gcangioli** [hl7-eu/unicom-ig#73]
In several profiles the vocabulary binding is done at the level of coding.code 
or a fixed system is used

![image](https://user-images.githubusercontent.com/35879607/207557493-a77e7298-def1-488b-986f-c1d15c987967.png)

I suggest to revise these profiles and  use - as needed - a value set binding at the level of CodeableConcept

**Comment by gcangioli** [comment]
updated the profiles in profiles.fsh
added new value sets

**Comment by rlindstrm** [comment]
I merged your changes to mpd-r4b branch, so I could make my changes on top of yours and make sure they work together.
I did the manual merge together with my changes, I really hope I didn't forget anything.
A few bindings still need to be fixed, I'll take care of those very soon.

**Comment by costateixeira** [comment]
closed in R4B and merged
