### ISSUE TITLE
Data from Italy

### ISSUE THREAD

**Issue by rlindstrm** [hl7-eu/unicom-ig#77]
Italian data in Excel format is [here ](https://github.com/unicom-project-eu/source-data/tree/main/Data%20As%20Is/ITA)
Little more than half of that data is in [6.1 database](https://unicom.datawizard.it/fhir/swagger-ui/), but needs to be improved to go through FHIR validation. 

See 6.1 import/transformation logic and ask Francesco about challenges they've already overcome.
Prefer SPOR codes (or provide appropriate code system).

Focus on the selection of 4 substances  (amlodipine, carbamazepine, ibuprofen, simvastatine), which should be 242 medicinal product packages: 
•	amlodipine 91 
•	carbamazepine 7 
•	ibuprofen  39
•	simvastatine 105.

(issue created/assigned according to what was agreed in the meeting, please react if I got something wrong)
Linked to #69.

**Comment by rlindstrm** [comment]
DataWizard is starting new import from Italian data.

**Comment by simodiaco** [comment]
The Italian data are on the server, maybe a few things need to be fixed, but we can use them for testing.
Later I will update the repo with the uploaded data file.
