### ISSUE TITLE
Ingredient

### ISSUE THREAD

**Issue by costateixeira** [hl7-eu/unicom-ig#8]
Draft description: 
From the ISO logical model and from discussion including in the latest FHIR Connectathon, having a separate Ingredient resource, while we can make it work, seems unnatural and not following the expected way the data is usually taken. 
The link FROM the resources TO Ingredient seemed more natural, but this was changed. After several discussions, it seems that the Ingredient is needed under ManufacturedItem and AdministrableProduct (where it has slightly different meanings and sometimes the same data, sometimes not - example the ingredients in the solvable product vs the ingredients in the prepared solution) . Can this Ingredient resource be collapsed under those 2 resources?

**Comment by gcangioli** [comment]
https://jira.hl7.org/browse/FHIR-39138

**Comment by costateixeira** [comment]
This is resolved. Ingredient stays because it is perceived as convenient
