### ISSUE TITLE
AdministrableProductDefinition - only 1 route of administration allowed

### ISSUE THREAD

**Issue by rlindstrm** [hl7-eu/unicom-ig#80]
Number 1 solved.
Number 2 not. (Changed the name of the issue for number 2)

1) MedicinalProductDefinition profiles (strict and relaxed both) don't show [Snapshot view](https://build.fhir.org/ig/hl7-eu/unicom-ig/branches/mpd-r4b/StructureDefinition-TransitionMedicinalProductDefinition.html) in the IG. 
Other profiles seem to work as normal.

2) In qa, there is an error "Rule apd-1: 'RouteOfAdministration cannot be used when the 'formOf' product already uses MedicinalProductDefinition.route (and vice versa)' Failed".
However, I do not have route of administration defined in two places, but I have two routes of administration in one place, which is perfectly legit. When I comment out one of the routes, the error disappears from qa.
The problematic administrable product is [here](https://github.com/hl7-eu/unicom-ig/blob/mpd-r4b/input/fsh/examplesSingleProfiles.fsh#L176), the corresponding medicinal product can be found a [few lines upwards](https://github.com/hl7-eu/unicom-ig/blob/mpd-r4b/input/fsh/examplesSingleProfiles.fsh#L133).

I'm not sure if they're publisher issues or if I'm doing something wrong.

**Comment by rlindstrm** [comment]
Number 2 already reported by José. Thank you! :)
https://jira.hl7.org/browse/FHIR-39755

**Comment by costateixeira** [comment]
I think #1 is fixed, but currently the publisher never finishes the entire
build so what we have online is still a broken version

**Comment by rlindstrm** [comment]
Mpd-r4b builds well I think. Took under 2 min for my local version, and online build showed thumbs-up as well. 
I updated publisher on the 31st. Should I try again?

**Comment by costateixeira** [comment]
online build of mpd-r4b is not ok:
![image](https://user-images.githubusercontent.com/16153168/210248404-d8e606c7-4f9b-434e-a42b-b4a9b750b0e7.png)

**Comment by costateixeira** [comment]
I will recheck why my build was failing. Seems that the problem is on my
end.
In any case, the snapshot view is there, it seems

**Comment by rlindstrm** [comment]
I see it works in mpd-r5 for example, but not in mpd-r4b branch (see [this](https://build.fhir.org/ig/hl7-eu/unicom-ig/branches/mpd-r4b/StructureDefinition-PPLMedicinalProductDefinition.html)). 
The Snapshot Table does not appear for me:
![image](https://user-images.githubusercontent.com/112903984/210249975-4bd4db47-266a-4e02-9cac-6ad8751ac707.png)

**Comment by rlindstrm** [comment]
About the Snapshot view problem. I have come to conclusion that it's the slicing on coding (EMA and WHO ATC) that causes this. I removed slicing from TransitionMedicinalProductDefinition profile and the Snapshot view started working.
Also, the same slicing confuses the terminology binding a little bit, because the example binding in the FHIR resource is on higher level (that will be in #84).
I am not smart enough to check if everything is correct with the slicing. It looks legit to me, but I'd be thankful if someone investigated it.

**Comment by rlindstrm** [comment]
Problem1. I killed the slicing on classification, so the snapshot view is back.

**Comment by rlindstrm** [comment]
Number 2 is solved in R5 build, Snapshot3 still has that problem, so  we're stuck with it until the next release.
