### ISSUE TITLE
Data from Portugal

### ISSUE THREAD

**Issue by rlindstrm** [hl7-eu/unicom-ig#82]
The source data from PT is here: https://github.com/unicom-project-eu/source-data/tree/main/Data%20As%20Is/PRT

The data has been created by the PT NCA,based on PPL list, very IDMP-like, should be easy to import. Also provides WHO and RMS codes for ATC. 

We can start with simple solid dose forms, or if the data is clear enough, we can do everything at once. We can discuss what's better.

It will also be an excellent way to break José's ( @costateixeira ) visualiser, because it has marketing authorisation on package level. It's something we haven't tried yet. :)

**Comment by joofio** [comment]
https://github.com/joofio/pplCreator/tree/r5/input/fsh/pt

**Comment by rlindstrm** [comment]
@joofio is done with the data, available in his project.
Once DW server gets stronger and faster, the results can be uploaded there.

**Comment by rlindstrm** [comment]
PT data has been finalised and is available. See UNICOM Toolbox.
