### ISSUE TITLE
Container per Country

### ISSUE THREAD

**Issue by a-gkogkidis** [hl7-eu/unicom-ig#99]
Can we have a container for each country instead of all the data in one database?
That would help also to reduce the complexity of searching in the database for each country.

For example:
jpaestona.unicom....
jpasweden.unicom...
jpagreece.unicom...
jpaitaly.unicom....

Is it possible to split the data by country before the import?

**Comment by costateixeira** [comment]
To get data from a country, we can simply add a search parameter. Besides,
I think we would better show the data coming together, same rules, etc.
Not sure what separating the DB adds (it simplifies things not but may make
later realignment harder)

**Comment by a-gkogkidis** [comment]
Well, the idea eventually is that each MS will have their own database, etc. So searching now by country is possible, but personally, I would prefer to have N endpoints for each country instead of one central. Based on the initial design of course. So, I ask jpagreece.uniocom.w/e/fhir, I know that there I can find only Greek data, ask jpaestonia.unicom/w/e/fhir I expect to find only Estonian data. etc. 

Already in DW R5 implementation, it's working like this.

**Comment by costateixeira** [comment]
I think DW split of the db could make alignment difficult so implicitly i'm
challenging whether this was needed and useful.
We can do it but do we need that hard split? in practice this is one server
per country. We can do that, of course. Wondering if there's any advantage

**Comment by rlindstrm** [comment]
@a-gkogkidis If the search function showed in the meeting was good enough, you can close the issue.
If not, we'll keep talking.

**Comment by a-gkogkidis** [comment]
it works just tested. I will leave a screenshot here for future reference if needed (its Java code..)

![image](https://user-images.githubusercontent.com/116799621/215102843-c2c57491-8172-4a24-965c-1d1c79cce18b.png)
